### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by eliluminado** [youtube-dlg/youtube-dl-gui#4]
I thought about making a new configuration window to discard the current multiple tabs, by a slightly more modern like this.

Any suggestions?

![uyf1s](https://cloud.githubusercontent.com/assets/424160/16179339/df424632-3638-11e6-9b15-7413b2c18cf8.png)

**Comment by serpico1** [comment]
Its there a new gui you are going to release?
I have some suggestions about it if you are interested. Im not a programmer at all but I have some ideas about the gui.

**Comment by nodiscc** [comment]
@serpico1 It is planned to [rewrite the application](https://github.com/youtube-dlg/youtube-dl-gui/issues/1), using another toolkit, so now might be a good time to suggest things. Please do it in this issue.

**Comment by nodiscc** [comment]
@eliluminado I think that having many tabs in the configuration window is confusing (too many clicks required to access an option, it takes a long time to find out where an option is). I'd say all options should remain accessible from a single window/tab.

**Comment by eliluminado** [comment]
It is in development, for now I'm working in the new configuration window and looks like this

![captura de pantalla de 2016-06-20 02-31-56](https://cloud.githubusercontent.com/assets/424160/16184060/709261fc-368f-11e6-8a7f-6b0446d6c8ca.png)

The idea is to give colors with CSS and compress the tabs options to a few, for example there is a tab where this only language selector

Any suggestions can be useful

**Comment by nodiscc** [comment]
@eliluminado I've created a new branch [qt-rewrite](https://github.com/youtube-dlg/youtube-dl-gui/tree/qt-rewrite). Can you send your code as a Pull Request on this branch? Thanks.

**Comment by nodiscc** [comment]
Moved from #1

> @farseenabdulsalam commented 19 hours ago 

>I have a suggestion. 
>I feel that the current UI is a little bit boring.
>If we are going to rewrite the UI code, we should redesign it to be something like this.

![FDM UI] 
(http://www.freedownloadmanager.org/public/img/screen_win.png)

**Comment by serpico1** [comment]
Youtube DLG is easy and good to use but I miss som functions.
Delete downloaded files from download list when they are finished.
Change maximum simultaneous downloads.
An option to choose subtitles for each file and select between the resolution on file to download.
SVT play use wsrt instead of srt for some reason. It is possible to build an converter which convert from wsrt to srt maybe.

**Comment by nodiscc** [comment]
@serpico1 Thank you, all these suggestions look good, except the last one (which looks like a job for another tool, a wsrt to srt converter)

About

>  An option to choose subtitles for each file and select between the resolution on file to download.

You can already select the resolution by adjusting the quality setting.

Having different languages for each download in the list is not possible as far as I know, because `youtube-dl` does not allow it, you have to run youtube-dlg multiple times with the correct subtitle settings (same as the command-line tool).

**Comment by serpico1** [comment]
@nodiscc 
Hi
About the resolution i mean an easy option when download file now must i choose both the resolution for the Movie and the audio separately its not easy to know what to choose. Ex i download hd and that is 1280*720 which audio should i use?

Are you going to continue with Youtube dl or are you going to make a own one for the new gui you want to make?

**Comment by eliluminado** [comment]
My idea would be possible to set individually from the download list, the video format.

**Comment by nodiscc** [comment]
>  i choose both the resolution for the Movie and the audio separately its not easy to know what to choose.  Ex i download hd and that is 1280*720 which audio should i use?

If you select a video format, the resulting video will _always_ use the audio track embedded in the video file ([Examples of audio/video codecs correspondence for youtube videos](https://en.wikipedia.org/wiki/YouTube#Quality_and_formats)). The audio format setting has no effect for video downloads.

If you check `Convert to audio`, ffmpeg will be used to do the conversion with the selected audio format and quality. (unless the source site already has a track in your selected audio format, in which case there will be no conversion and the original audio will simply be downloaded, or demuxed from the video).

Maybe we should document this in a FAQ.

Note that youtube-dl-gui currently misses some format options (eg. bestaudio/bestvideo, etc., check https://github.com/rg3/youtube-dl#format-selection).

> Are you going to continue with Youtube dl or are you going to make a own one for the new gui you want to make?

I think we should try to fix existing bugs in youtube-dl-gui, but should not try too hard as it's planned to rewrite it with another toolkit (#5). If this is what you're asking, [youtube-dl](https://github.com/rg3/youtube-dl) will still be used for downloads, it is extremely high quality software. youtube-dl-gui, is just, well, a GUI.

**Comment by nodiscc** [comment]
@eliluminado 

> My idea would be possible to set individually from the download list, the video format.

Maybe there should be a `Format` selection list near the `Paste URLs to download` field. It should be set by default to the default format specified in Options. When the user hits `Download`, all URLs in the `Add URLs` field will start downloading using the selected format; and the `Format` selection list will reset to the default value.

**Comment by serpico1** [comment]
@nodiscc 
I think YoutubeDLG its good enough with some changes. Maybe you don't need to create a complete new program its easier to make some changes in existing program. Thanks for answer on my questions. I look forward to the updated gui.

**Comment by eliluminado** [comment]
The problem I see with the current code is the huge number of patches, and a too minimalist interface. Although this last could fix it by having an option to enable an advanced interface and other more simple.

**Comment by serpico1** [comment]
@eliluminado
Its there patches to download for Youtube DLG or have i missunderstand. Does YoutubeDLG vas updated since a year ago? I Think its only Youtube dl vas updated.

**Comment by eliluminado** [comment]
The new interface changes are not reflected in this repository, you can try it from here https://github.com/eliluminado/youtube-dl-gui.

**Comment by serpico1** [comment]
@eliluminado
Do you make a updated gui or what? Can i use your version and what are the different from original?

**Comment by eliluminado** [comment]
Not yet, first I'm developing the interface and then connect all features of youtube-dl.

**Comment by serpico1** [comment]
@eliluminado
I suppose you write here when you are finish with the program i look forward to that. 
I also wonder if the gui can do the same that the Youtube DL can if i dont use the gui. I dont have used Youtube DL i only have used the Youtube DLG because its much easier to use . 

I also wonder if i download from Swedish playsites which i often do. Can the file i download 
distinguish dependent which program i use to download it or not. I am not a programmer so i dont know exactly how it works when to downloads from playsites. I am very happy that someone can make a program which easy can make downloads from playsites.





dis

**Comment by philipzae** [comment]
I'm a UI and UX designer and i'd like to assist in anyway possible, as i've been using an alternative youtube-dl app ( https://code.google.com/archive/p/ytd-gtk/downloads ) that hasnt been updated in a while. I had also tried this other python GUI - https://code.google.com/archive/p/youtube-dl-gui/

@eliluminado the vertical tabs rather than the old horizontal tabs in the preferences is a step in the right direction.

On Windows i used to use YTD ( youtubedownloadersite.com ) and believe their interface was close to perfect, though the tabs arent crucial.
http://www.youtubedownloadersite.com/images/new-ytd-screen.jpg
http://screenshots.en.sftcdn.net/en/scrn/54000/54977/ytd-video-downloader-03-700x530.png

The first thing that needs to be done is to move the video and audio settings out of options and bring it into the main window, as users may want to download the video of one url but the audio of a second url, so a user shouldnt have to go into the options dialog constantly to change this.

The second thing to be dealt with is to have buttons to manage the download list. Buttons for pause, resume, delete, redownload, move up, move down, clear, and play are needed. The play button would play the completed media in the default associated player or alternatively with the video and audio players set in the options dialog.

The third thing is to decide whether simultaneous downloads is wanted/needed and whether a queue is better.

Let me know if more suggestions are wanted.

**Comment by nodiscc** [comment]
> the vertical tabs rather than the old horizontal tabs in the preferences is a step in the right direction.
> move the video and audio settings out of options and bring it into the main window
> buttons to manage the download list

:+1: (except maybe reordering the downloads list is not needed?)

> decide whether simultaneous downloads is wanted/needed

I think it is needed. A request to make the number of concurrent downloads can be found in the original repo. Example use case: you have a long download running (https://www.youtube.com/watch?v=yrgaD9I_CtI :) ) but don't want it to block the rest of them.

> Let me know if more suggestions are wanted.

Yes!

**Comment by philipzae** [comment]
> :+1: (except maybe reordering the downloads list is not needed?)

Reordering isnt needed if you have no limit on concurrent downloads.

> I think it is needed. A request to make the number of concurrent downloads configurable can be found in the original repo. Example use case: you have a long download running (https://www.youtube.com/watch?v=yrgaD9I_CtI :) ) but don't want it to block the rest of them.

As you can pause downloading a longer video in the queue and then reorder it to the bottom of the list and then unpause it, or alternatively just move it to the bottom of the list while its downloading, there isnt a problem. This is the common behaviour in most download managers and bittorrent clients. Concurrent downloads is very useful when you download a file from different servers, but as all would be coming from the same server, it wont increase the download speeds of the downloads, but it is a good setting for those who want to use it, but i would suggest the the concurrent downloads be set to 1 by default.

> Yes!

1) playlist dialog - this dialog would allow a user to enter in a url and then a list would be populated with the videos in the playlist, so that a user can select which videos in the playlist then want to download. presently if you give the app a playlist url, it will download all the videos in playlist.

2) update button - this should be moved into the settings as it is vague and is for updating youtube-dl and not the GUI app

I'll be working on a mockup, which i hope i can present to you in the next couple of days.

**Comment by philipzae** [comment]
Working on the ideas and mockup here for all those who want to see it - https://docs.google.com/document/d/1UJ55sYepfk5Dl0nCJNz9fXRBgpG32v-4RwIqSdkXXVg/edit?usp=sharing

**Comment by philipzae** [comment]
Here is the mockup and i think it is pretty much complete. Some additional tweaks maybe needed and feedback is appreciated.

![ydlg mockup](https://cloud.githubusercontent.com/assets/4412114/16716153/8ad0e8c8-4705-11e6-94d2-52c8d0b283ce.png)

**Comment by serpico1** [comment]
Loog great Clean and easy gui. 
I wonder what the option for example mp4/320p and webm/320p meaning  Its in current gui also but i dont know what its the different.
Maybe you also inplement this:https://github.com/youtube-dlg/youtube-dl-gui/issues/9.

Do you have an resume option?
The output function on renaming files are not easy to understand in current gui. A lot of % character how knows  what that mean?
An option to manually rename files when downloading should be great as optional.
Its just my suggestions.

**Comment by philipzae** [comment]
> I wonder what the option for example mp4/320p and webm/320p meaning Its in current gui also but i dont know what its the different.

mp4 and webm are the container formats the video is encoded in on youtube and it is possible for a user to download a particular format if they choose. 320p is the video height/quality. in the mockup i didnt include every single format that is possible like is there in the options dialog, as it would be quite confusing to most users to see such a long list, but there could be a toggle option in the options dialog to show the complete list. some formats that should be in the list were left out in the mockup due to space, but they would definitely need to be there like m4a and ogg audio and their various bitrates.

> Maybe you also inplement this:#9.

Similar to how it works now, if you enable subtitle download in the options dialog, it will skip redownload the video if its in the same folder, so i'm not sure what is intended here. Also i couldnt find a specific commandline argument for youtube-dl to only download subtitle.

> Do you have an resume option?

Yes the pause button will change into a resume button if a selected entry in the download list has been placed on pause.

> The output function on renaming files are not easy to understand in current gui. A lot of % character how knows what that mean?

Yes i planned to submit a number of file naming options for inclusion in the options dialog like the below.
Title + Quality (%(title)s-%(height)sp.%(ext)s) [i'd recommend this be the default]
Title + ID (%(title)s-%(id)s.%(ext)s) [i used to use this one till a few days back]
Title + ID + Quality (%(title)s-%(id)s-%(height)sp.%(ext)s) [i started using this one a few days back, so i could download different quality versions of the same video]
Of course the naming strings above would be hidden from users.

> An option to manually rename files when downloading should be great as optional.

I would recommend leaving such a feature to the file manager.

> Its just my suggestions.

Thanks for the input.

**Comment by serpico1** [comment]
About the subtitles to download later. I mean if you have already downloaded files which you have moved and maybe change name on. And then you need subtile later. The program cant find the files in the directory if they are moved and the name changed and i only need subtiles for them. 

About the mp4 or webm. It´s there just two different container or which its the best i have only used mp4 and it works fine in bluray player.

I look forward to the updated gui hope it coming soon.

**Comment by philipzae** [comment]
> About the subtitles to download later. I mean if you have already downloaded files which you have moved and maybe change name on. And then you need subtile later. The program cant find the files in the directory if they are moved and the name changed and i only need subtiles for them.

Yes i do understand what you mean about this, but i'm assuming the developers of this GUI wont be implementing features not available in the underlying youtube-dl commandline tool, but if they do, the toggling of this feature would likely be left for the options dialog as it isnt a feature that most users need access to for each download. I believe that users wont need to rename downloaded files, if we provide them with a good default naming of files like Title + Quality or Title + ID.

> About the mp4 or webm. It´s there just two different container or which its the best i have only used mp4 and it works fine in bluray player.

No there are other containers like 3gp and flv that are available for download, as well as containers the downloaded files can be converted to like mkv and avi. mp4 and webm are html5 video container formats and the most popular used formats for online video presently. < https://en.wikipedia.org/wiki/HTML5_video >

**Comment by serpico1** [comment]
When i download from example svtplay and choose mp4 it´s the file i downloaded stored on server as mp4 or do the program lika Youtube dl the file to mp4 or webm which i choose?
Thanks for all good answer.

**Comment by nodiscc** [comment]
>  I wonder what the option for example mp4/320p and webm/320p meaning Its in current gui also but i dont know what its the different.

https://github.com/rg3/youtube-dl#format-selection

@philipzae I suggest that only the common aliases (`best worst bestvideo worstvideo bestaudio worstaudio`) should be listed in the formats list. The formats are extractor specific and you are supposed to get these using `--list-formats`. Setting a youtube-specific format will cause the download to fail on other sites, or will trigger re-encoding with ffmpeg. Most of the time this is not needed. For ease of use the common formats could be added (3gp, aac, flv, m4a, mp3, mp4, ogg, wav, webm).

I believe adding these values and replacing `default` by `best` is the most pressing issue. Most users will not use the format options in hopes to get a better quality.

> The output function on renaming files are not easy to understand in current gui. A lot of % character how knows what that mean?

@serpico1 https://github.com/rg3/youtube-dl#output-template - all possible values are detailed here.

@philipzae A link to https://github.com/rg3/youtube-dl#output-template in the settings dialog would help knowing about this. A few default naming presets in the dropdown list/textarea would be welcome, but it must also allow custom naming schemes. Currently you can set the destination filename with the above option.

>  Of course the naming strings above would be hidden from users.

I suggest displaying an example of the result below the output template field eg. `youtube-eMkdtMQH7WM -  Grand Theft Auto III - MSX FM (No Commercials) - LosGTARadio.ext`

> Also i couldnt find a specific commandline argument for youtube-dl to only download subtitle.
>     An option to manually rename files when downloading should be great as optional.
> About the subtitles to download later. 
>  i'm assuming the developers of this GUI wont be implementing features not available in the underlying youtube-dl commandline tool,

As far as I know youtube-dl does not implement this, so it is not planned to add it here.

@serpico1 you would have to rename the video to the expected, original filename, or re-download the video+subtitles. I suggest using a specialized tool, look at https://github.com/search?l=Python&q=youtube+subtitles&type=Repositories

> When i download from example svtplay and choose mp4 

What happens depends whether the server has an mp4 version available:

 * If yes, the original mp4 file will be downloaded from the server and left untouched.
 * If not, the program will download another (`best`?) video format, and convert it to mp4 after download, using ffmpeg (https://github.com/youtube-dlg/youtube-dl-gui/issues/8)

For most purposes you should leave the format to `best` (except if you have format support or bandwidth restrictions).

**Comment by philipzae** [comment]
> @philipzae I suggest that only the common aliases (best worst bestvideo worstvideo bestaudio worstaudio) should be listed in the formats list.

What would be the purpose of having bestvideo and worstvideo in the list if a video only file was downloaded? I tested `worst` on youtube videos and the result wasnt useful as it always downloaded a 3gp file, though i can imagine it coming in handy when downloading from other video sites which have one container format with various sizes/qualities (e.g. vimeo).

> The formats are extractor specific and you are supposed to get these using --list-formats. Setting a youtube-specific format will cause the download to fail on other sites, or will trigger re-encoding with ffmpeg. Most of the time this is not needed. For ease of use the common formats could be added (3gp, aac, flv, m4a, mp3, mp4, ogg, wav, webm).

Yes having a mix of aliases and youtube-specific formats would be most useful to cater to both types of users, as some users will prefer to download specific formats or specifically open source formats, but would suggest we restrict the list to commonly used formats like mp4, webm, m4a, mp3 and ogg.

> @philipzae A link to https://github.com/rg3/youtube-dl#output-template in the settings dialog would help knowing about this. A few default naming presets in the dropdown list/textarea would be welcome, but it must also allow custom naming schemes. Currently you can set the destination filename with the above option.

It would be preferable to include relevant text about the naming within the setting dialog. Yes of course it wouldnt suggest removing the custom naming scheme option.

> I suggest displaying an example of the result below the output template field

Yes that would be useful. Also thought we might want to include a series of drop down menus for the custom naming scheme, so a user could easily pick the sequence of the resulting filename.

> @philipzae great work on the mockups. I will probably have some time in the next few months to work on youtube-dl-gui.

Glad to be part of the process, as i've been eager to use a great youtube-dl GUI since i moved over to linux. I will be working on a separate mockup for playlist video selection which i hope can also be implemented.

**Comment by serpico1** [comment]
@philipzae 
When do you Think the new gui is ready to release?

**Comment by nodiscc** [comment]
@serpico1 There is no ETA yet. Probably before the end of 2016.

**Comment by serpico1** [comment]
@nodiscc 
i will  have patience.
